site_name: Perfect Media Server
repo_url: https://github.com/IronicBadger/pms-wiki
repo_name: ironicbadger/pms-wiki

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/regular/save
    favicon: fontawesome/regular/save
  palette:
    primary: indigo
    accent: teal
    scheme: default
  font:
    code: Jet Brains Mono
  features:
    - navigation.instant
    #- navigation.sections # prevents collapsible sections
    #- navigation.expand #expands sections by default
  # insiders only
  #   - search.suggest

google_analytics: ['G-DF6SGTVVBC', 'soon.perfectmediaserver.com']

plugins:
  - git-revision-date
  - search
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - admonition # enables coloured blocks mid article
  - attr_list # improves image handling
  - pymdownx.details # enables collapsible admonitions
  - footnotes
  - meta # adds support for front matter
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight: # code highlighting
      linenums: true
  - pymdownx.tabbed # enables tabs for embedded blocks
  - pymdownx.snippets
  - pymdownx.superfences # allows for the nesting of code blocks inside other blocks
  - pymdownx.keys

copyright: 2020 - 2021 &copy; Alex Kretzschmar - Licensed under GPLv3
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/ironicbadger'
      name: IronicBadger on GitHub
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/ironicbadger'
      name: IronicBadger on Twitter
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/alex-kretzschmar/'      
    - icon: 'fontawesome/solid/microphone'
      link: 'https://selfhosted.show/'
      name: IronicBadger's Podcast - selfhosted.show

nav:
  - Introduction: 
    - Welcome: 'index.md'
    - PMS Overview: 'overview/overview.md'
    - FAQ: 'overview/faq.md'
  - Tech Stack:
    - Docker: 'tech-stack/docker.md'
    - MergerFS: 'tech-stack/mergerfs.md'
    - SnapRAID: 'tech-stack/snapraid.md'
    - ZFS: 'tech-stack/zfs.md'
    - Proxmox: 'tech-stack/proxmox.md'
  - Hardware:
    - New Drive Burn-In Rituals: 'hardware/new_drive_burnin.md'
  - Installation:
    - Bare Metal Manual Install: 'installation/manual-install.md'
    - Manual Install on Video: 'installation/manual-install-on-video.md'
    - Automated Install: 'installation/automated-install.md'
  - Day Two (Post Install):
    - Remote Access: 'day-two/remote-access.md'
    - Quality of Life Tweaks: 'day-two/quality-of-life-tweaks.md'
  - Advanced Concepts:
    - Infrastructure as Code: 'concepts/infraascode.md'
    - Hypervisors: 'concepts/hypervisors.md'
    - PCI Passthrough: 'concepts/pci-passthrough.md'
  - Advanced Configuration:
    - Using ZFS with MergerFS: 'advanced/combine-zfs-and-others.md'
    - Quick Sync and Proxmox passthrough: 'advanced/passthrough-igpu-gvtg.md'
  - Related Projects:
    - Virtualised OPNsense router: 'related-projects/virtualised-opnsense-proxmox.md'